spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ← ЭТО ОБЯЗАТЕЛЬНО
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyzer-snapshots
      auto-offset-reset: earliest
      enable-auto-commit: false

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext